nobre1 = float(input("Veillez entrer la premiere valeur:"))
nbre2 = float(input("Veillez entrer la seconde valeur:"))
A = (nobre1+nbre2)
P = (nobre1*nbre2)
S = (nobre1-nbre2)
D = (nobre1/nbre2)
print("La somme est:",A)
print("Le Produit est:", P)
print("La soustraction est:",S)
print("La division est:", D)